EStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# Static
from django.conf.urls.static import static
from django.conf import settings

# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register('products', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customers.urls')),
    path('', include('users.urls')),
    path('', include('cart.urls')),
    path('', include('checkout.urls')),
    path('', include('dashboard.urls')),
    path('', include('report.urls')),
    path('', include('analysis.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest-framework')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# Static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *


app_name = 'cart'
urlpatterns = [
    path('gio-hang/', cart_detail, name='cart_detail'),
    path('buy_now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove_cart/<int:product_id>/', remove_cart, name='remove_cart'),
]

checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('success/', views.success, name='success'),
]

customers/urls.py
from django.urls import path
from customers.views import *


app_name = 'customers'
urlpatterns = [
    path('dang-nhap/', login, name='login'),
    path('dang-xuat/', logout, name='logout'),
    path('tai-khoan/', my_account, name='my_account'),
]

store/urls.py
from django.urls import path
from store.views import *

app_name = 'store'

urlpatterns = [
    path('', index, name='index'),
    path('danh-muc/<str:slug>/', product_list, name='product_list'),
    path('san-pham/<int:pk>/', product_detail, name='product_detail'),
    path('lien-he/', contact, name='contact'),
    path('tim-kiem/', search, name='search'),
    path('rss/', read_rss, name='rss'),
    path('products-service/', products_service, name='products_service'),
    path('product-service/<int:pk>/', product_service, name='product_service'),
]

checkout/models.py
from django.db import models
from store.models import Product
import uuid


class Order(models.Model):
    username = models.EmailField(null=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=500, unique=False)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,  unique=True, primary_key=True, editable=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

store/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=150)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    subcategory = models.ForeignKey(SubCategory, on_delete=models.PROTECT)
    name = models.CharField(max_length=250)
    price = models.FloatField(default=0.0)
    price_origin = models.FloatField(null=True)
    image = models.ImageField(upload_to='store/images', default='store/images/default.png')
    content = RichTextUploadingField(blank=True, null=True)
    public_day = models.DateTimeField(default=timezone.now)
    viewed = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, null=True)
    subject = models.CharField(max_length=264)
    message = models.TextField()

    def __str__(self):
        return self.name + ", " + self.subject

checkout/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Username', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter username',
    }))

    first_name = forms.CharField(max_length=50, label='first_name', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    
    last_name = forms.CharField(max_length=50, label='last_name', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))

    phone = forms.CharField(max_length=20, label='Phone number', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))

    address = forms.CharField(max_length=500, label='Address', widget=forms.Textarea(attrs={
        'class': 'form-control',
    }))
    
    class Meta:
        model = Order
        fields = ['username', 'first_name', 'last_name', 'phone', 'address']

customers/forms.py
from django import forms
from customers import models


class FormDangKy(forms.ModelForm):
    ho = forms.CharField(max_length=250, label='Họ', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Họ"
    }))
    ten = forms.CharField(max_length=250, label='Tên', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Tên"
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Email"
    }))
    mat_khau = forms.CharField(max_length=100, label='Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Mật khẩu"
    }))
    xac_nhan_mat_khau = forms.CharField(max_length=100, label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Xác nhận Mật khẩu"
    }))
    dien_thoai = forms.CharField(max_length=20, label='Điện thoại', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Điện thoại"
    }))
    dia_chi = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Địa chỉ",
        "rows": 4,
    }))
    tinh_tp = forms.CharField(label='Tỉnh/TP', widget=forms.Select(attrs={
        "class": "form-control",
    }))
    quan_huyen = forms.CharField(label='Quận/Huyện', widget=forms.Select(attrs={
        "class": "form-control",
    }))
    phuong_xa = forms.CharField(label='Phường/Xã', widget=forms.Select(attrs={
        "class": "form-control",
    }))

    class Meta:
        model = models.Customer
        # fields = '__all__'
        fields = ['ho', 'ten', 'email', 'mat_khau', 'dien_thoai', 'dia_chi']


class FormThongTin(forms.ModelForm):
    ho = forms.CharField(max_length=250, label='Họ:', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Họ",
        "readonly": "readonly",
    }))
    ten = forms.CharField(max_length=250, label='Tên:', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Tên",
        "readonly": "readonly",
    }))
    email = forms.EmailField(label='Email / Tên đăng nhập:', widget=forms.EmailInput(attrs={
        "class": "form-control",
        "placeholder": "Email",
        "readonly": "readonly",
    }))
    dien_thoai = forms.CharField(max_length=20, label='Điện thoại:', widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder": "Điện thoại"
    }))
    dia_chi = forms.CharField(label='Địa chỉ:', widget=forms.Textarea(attrs={
        "class": "form-control",
        "placeholder": "Địa chỉ",
        "rows": 3,
        "style": "resize:none",
    }))

    class Meta:
        model = models.Customer
        fields = ['ho', 'ten', 'email', 'dien_thoai', 'dia_chi']


class FormDoiMatKhau(forms.ModelForm):
    mat_khau = forms.CharField(max_length=100, label='Mật khẩu cũ', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Mật khẩu cũ"
    }))
    mat_khau_moi = forms.CharField(max_length=100, label='Mật khẩu mới', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Mật khẩu mới"
    }))
    xac_nhan_mat_khau = forms.CharField(max_length=100, label='Xác nhận mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Xác nhận mật khẩu"
    }))

    class Meta:
        model = models.Customer
        fields = ['mat_khau',]

store/forms.py
from django import forms
from store import models
from django.core.validators import RegexValidator

phone_validator = RegexValidator(
    r"((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))", "Your phone number must be (xxx)xxxxxxxxx or 0xxxxxxxxx!")


class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=150, label='Name', widget=forms.TextInput(attrs={
        'placeholder': 'Họ tên',
        'class': 'form-control'
    }))
    phone_number = forms.CharField(max_length=20, label='Phone', validators=[phone_validator],
                                   widget=forms.TextInput(attrs={
                                       'placeholder': 'Điện thoại',
                                       'class': 'form-control fh5co_contact_text_box',
                                       'pattern': '((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))',
                                       'title': 'Your phone number must be (xxx)xxxxxxxxx or 0xxxxxxxxx'
                                   }))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={
        'placeholder': 'Email',
        'class': 'form-control'
    }))
    subject = forms.CharField(label='Subject', widget=forms.TextInput(attrs={
        'placeholder': 'Tiêu đề',
        'class': 'form-control'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Nội dung',
        'class': 'form-control',
        'rows': '5'
    }))

    class Meta:
        model = models.Contact
        fields = '__all__'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from store.models import Product
from django.views.decorators.http import require_POST
from django.conf import settings


# Create your views here.
def cart_detail(request):

    # Giỏ hàng
    cart = Cart(request)

    # Xử lý cập nhật khi có mã giảm giá
    coupon_code = ''
    if request.POST.get('btnCoupon'):
        coupon_code = request.POST.get('coupon')
        if coupon_code == 'HA':
            cart_new = {}
            for item in cart:
                product_new = {
                    str(item['product'].pk): {
                        'quantity': item['quantity'],
                        'price': str(item['product'].price),
                        'coupon': '0.9'
                    }
                }
                cart_new.update(product_new)
                item['coupon'] = 0.9
            else:
                request.session['cart'] = cart_new
        else:
            cart_new = {}
            for item in cart:
                product_new = {
                    str(item['product'].pk): {
                        'quantity': item['quantity'],
                        'price': str(item['product'].price),
                        'coupon': '1'
                    }
                }
                cart_new.update(product_new)
                item['coupon'] = 1
            else:
                request.session['cart'] = cart_new

    # Xử lý cập nhật dữ liệu
    if request.POST.get('btnUpdateCart'):
        cart_new = {}
        for item in cart:
            quantity_new = int(request.POST.get('quantity2_' + str(item['product'].pk)))
            if quantity_new != 0:
                product_new = {
                    str(item['product'].pk): {
                        'quantity': quantity_new,
                        'price': str(item['product'].price),
                        'coupon': '1'
                    }
                }
                cart_new.update(product_new)
            else:
                cart.remove((item['product']))
            item['quantity'] = quantity_new
        else:
            request.session['cart'] = cart_new

    return render(request, 'store/cart.html', {'cart': cart})


@require_POST
def buy_now(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('quantity'):
        cart.add(product=product, quantity=int(request.POST.get('quantity')))

    return redirect('cart:cart_detail')


@require_POST
def remove_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

checkout/views.py
from django.shortcuts import render, redirect
from cart.cart import Cart
from store.my_module import *
from .models import Order, OrderItem
from django.views.decorators.http import require_POST
from EStore.settings import EMAIL_HOST_USER
from django.core.mail import EmailMessage


def checkout(request):
    # Kiểm tra trạng thái đăng nhập của khách hàng
    session_status = check_session(request, 'sessionKhachHang')
    session_info = ''
    cart = Cart(request)
    if session_status and cart.__len__():
        session_info = request.session.get('sessionKhachHang')
    else:
        return redirect('cart:cart_detail')

    return render(request, 'store/checkout.html', {'session_info': session_info})


@require_POST
def success(request):
    # Kiểm tra trạng thái đăng nhập của khách hàng
    session_status = check_session(request, 'sessionKhachHang')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionKhachHang')
    else:
        return redirect('cart:cart_detail')
    cart = Cart(request)
    username = request.session['sessionKhachHang']['email']
    first_name = request.session['sessionKhachHang']['ho']
    last_name = request.session['sessionKhachHang']['ten']
    phone = request.session['sessionKhachHang']['dien_thoai']
    address = request.session['sessionKhachHang']['dia_chi']
    total = cart.get_final_total_price()
    order = Order.objects.create(username=username, first_name=first_name, last_name=last_name, phone=phone, address=address, total=total)
    order.save()

    for item in cart:
        order_item = OrderItem.objects.create(product=item['product'], order=order, price=item['total_price'], quantity=item['quantity'])
        order_item.save()
    subject = 'Chúc mừng ' + order.first_name + ' ' + order.last_name + ' đặt hàng thành công'
    content = '<p>' + order.address + ', tổng tiền là: ' + str(order.total) + '</p>'
    content += '''
        <table class="table">
          <thead>
            <tr>
              <th scope="col">STT</th>
              <th scope="col">Tên sản phẩm</th>
              <th scope="col">Số lượng</th>
              <th scope="col">Đơn giá</th>
              <th scope="col">Thành tiền</th>
            </tr>
          </thead>
          <tbody>'''
    for item in cart:
        content += '''<tr>
          <th scope="row">1</th>
          <td>''' + str(item['product']) + '''</td>
          <td>''' + str(item['quantity']) + '''</td>
          <td>''' + str(item['product'].price) + '''</td>
          <td>''' + str(item['total_price']) + '''</td>
        </tr>'''
    content += '''</tbody>
        </table>

    '''

    msg = EmailMessage(subject, content, EMAIL_HOST_USER, [order.username])
    msg.content_subtype = 'html'
    msg.send()

    cart.clear()

    return render(request, 'store/success.html')

store/templates/store/_Master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title_tab %}{% endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'store/images/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'store/lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'store/lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'store/css/style.css' %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        hadh31011999@gmail.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        +(84) 349 998 172
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->
        
        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'store:index' %}" class="nav-item nav-link active">Trang chủ</a>
                            <a href="{% url 'store:product_list' 'tat-ca-san-pham' %}" class="nav-item nav-link">Sản phẩm</a>
                            <a href="{% url 'store:contact' %}" class="nav-item nav-link">Liên hệ</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            {% if session_status %}
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ session_info.ho }} {{ session_info.ten }}</a>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'customers:my_account' %}" class="dropdown-item">Tài khoản</a>
                                        <a href="{% url 'customers:logout' %}" class="dropdown-item">Đăng xuất</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'customers:login' %}" class="nav-item nav-link">Đăng nhập</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->      
        
        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="{% url 'store:index' %}">
                                <img src="{% static 'store/img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="search">
                            <form method="get" action="{% url 'store:search' %}">
                                <input type="text" placeholder="Tìm kiếm sản phẩm..." name="tu_khoa" autocomplete="off" value="{{ tu_khoa }}" required>
                                <button type="submit"><i class="fa fa-search"></i></button>
                                {% comment %} Bạn đã ghé thăm website này {{ visits }} lần {% endcomment %}
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
{#                            <a href="wishlist.html" class="btn wishlist">#}
{#                                <i class="fa fa-heart"></i>#}
{#                                <span>(0)</span>#}
{#                            </a>#}
                            <a href="{% url 'cart:cart_detail' %}" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>({{ cart|length }})</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->       
        
        {% block content %}{% endblock %}
        
        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Thông tin liên hệ</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>860 Huỳnh Tấn Phát, phường Tân Phú, quận 7, TP.HCM</p>
                                <p><i class="fa fa-envelope"></i>hadh31011999@gmail.com</p>
                                <p><i class="fa fa-phone"></i>+(84) 349 998 172</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Thông tin cửa hàng</h2>
                            <ul>
                                <li><a href="#">Về chúng tôi</a></li>
                                <li><a href="#">Chính sách & điều khoản</a></li>
                                <li><a href="#">Quy định bảo hành</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Hỗ trợ khách hàng</h2>
                            <ul>
                                <li><a href="#">Hướng dẫn thanh toán</a></li>
                                <li><a href="#">Thông tin giao hàng</a></li>
                                <li><a href="#">Quy định đổi trả hàng</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Theo dõi chúng tôi</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                
                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>Chấp nhận thanh toán:</h2>
                            <img src="{% static 'store/img/payment-method.png' %}" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Bảo mật bởi:</h2>
                            <img src="{% static 'store/img/godaddy.svg' %}" alt="Payment Security" />
                            <img src="{% static 'store/img/norton.svg' %}" alt="Payment Security" />
                            <img src="{% static 'store/img/ssl.svg' %}" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->       
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'store/lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'store/lib/slick/slick.min.js' %}"></script>
        
        <!-- Template Javascript -->
        <script src="{% static 'store/js/main.js' %}"></script>
    </body>
</html>

store/templates/store/contact.html
{% extends 'store/_Master.html' %}
{% block title_tab %}Liên hệ{% endblock %}
{% load static %}


{% block content %}
        
    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Trang chủ</a></li>
                <li class="breadcrumb-item active">Liên hệ</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Contact Start -->
    <div class="contact">
        <div class="container-fluid">
            <div class="row">
                
                <div class="col-lg-5">
                    <div class="contact-info">
                        <h2>Cửa hàng của tôi</h2>
                        <h3><i class="fa fa-map-marker"></i>860/16 Huỳnh Tấn Phát, phường Tân Phú, quận 7, TP.HCM</h3>
                        <h3><i class="fa fa-envelope"></i>hadh31011999@gmail.com</h3>
                        <h3><i class="fa fa-phone"></i>+ (84) 349 998 172</h3>
                        <div class="social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="contact-form">
                        <form>
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" class="form-control" placeholder="Tên của bạn" />
                                </div>
                                <div class="col-md-6">
                                    <input type="email" class="form-control" placeholder="Địa chỉ E-mail" />
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Tiêu đề" />
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" rows="5" placeholder="Nội dung"></textarea>
                            </div>
                            <div class="text-center">
                                <button class="btn" type="submit">Gửi thông tin</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="contact-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3164.2394748027764!2d106.73058930947059!3d10.72759528090378!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752565caeb825f%3A0x8e71399d04c059c3!2zODU4IEh14buzbmggVOG6pW4gUGjDoXQsIFTDom4gUGjDuiwgUXXhuq1uIDcsIFRow6BuaCBwaOG7kSBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1630856971885!5m2!1sen!2s" class="map_sss" allowfullscreen></iframe>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
        
{% endblock %}

store/templates/store/success.html
{% extends 'store/_Master.html' %}
{% load static %}

{% block title %}Mua hàng thành công{% endblock title %}

{% block content %}
    <!-- Breadcrumb Start -->
    <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
                <li class="breadcrumb-item active">Đặt hàng</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkout Start -->
    <div class="checkout">
        <div class="container-fluid">
            <div class="text-center">
                <img src="{% static 'store/images/success.png' %}" width="20%" />
                <p><h2>Đặt hàng thành công</h2></p>
                <p><h4>Cảm ơn bạn đã đặt hàng. Đơn hàng của bạn sẽ được chuyển đến bạn trong thời gian sớm nhất.</h4></p>
                <br>
            </div>
        </div>
    </div>

{% endblock content %}