EStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# Static
from django.conf.urls.static import static
from django.conf import settings

# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register('products', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customers.urls')),
    path('', include('users.urls')),
    path('', include('cart.urls')),
    path('', include('checkout.urls')),
    path('', include('dashboard.urls')),
    path('', include('report.urls')),
    path('', include('analysis.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest-framework')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# Static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *


app_name = 'cart'
urlpatterns = [
    path('gio-hang/', cart_detail, name='cart_detail'),
    path('buy_now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove_cart/<int:product_id>/', remove_cart, name='remove_cart'),
]

dashboard/urls.py
from django.urls import path
from .views import dashboard_with_pivot, pivot_data

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', dashboard_with_pivot, name='dashboard'),
    path('pivot_data/', pivot_data, name='pivot_data')
]

dashboard/views.py
from django.shortcuts import render
from store.models import Product
from django.core import serializers
from django.http import JsonResponse


def dashboard_with_pivot(request):
    return render(request, 'dashboard/dashboard-with-pivot.html')


def pivot_data(request):
    dataset = Product.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

dashboard/templates/dashboard/dashboard-with-pivot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard with pivot</title>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <link href="https://cdn.flexmonster.com/flexmonster.min.css" rel="stylesheet">
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'dashboard:pivot_data' %}"></div>
<div id="pivot-chart-container"></div>

<script>
    function processData(dataset) {
        var result = []
        dataset = JSON.parse(dataset);
        dataset.forEach(item => result.push(item.fields));
        return result;
    }

    $.ajax({
        url: $('#pivot-table-container').attr('data-url'),
        dataType: 'json',
        success: function (data){
            new Flexmonster({
                container: 'pivot-table-container',
                componentFolder: 'https://cdn.flexmonster.com/',
                width: '100%',
                height: 430,
                toolbar: true,
                report: {
                    dataSource: {
                        type: 'json',
                        data: processData(data),
                        mapping: {
                            'name': {
                                'caption': 'Tên sản phẩm',
                                'type': 'string'
                            },
                            'price': {
                                'caption': 'Giá',
                                'type': 'number'
                            },
                            'viewed': {
                                'caption': 'Lượt xem',
                                'type': 'number'
                            }
                        },
                    },
                    slice: {}
                }
            });
            new Flexmonster({
                container: 'pivot-chart-container',
                componentFolder: 'https://cdn.flexmonster.com/',
                width: '100%',
                height: 430,
                //toolbar: true,
                report: {
                    dataSource: {
                        type: 'json',
                        data: processData(data),

                    },
                    slice: {},
                    'options': {
                        'viewType': 'charts',
                        'chart': {
                            'type': 'pie',
                        }
                    }
                }
            });
        }
    })
</script>
</body>



</html>